# Generated by Django 4.2.4 on 2023-08-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_adress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_struc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstApp.adress'),
        ),
    ]
